name: tregs
channels:
  - default
dependencies:
  - python>=3.9
  - biopython=1.81
  - contourpy=1.0.7
  - cycler=0.11.0
  - fonttools=4.39.3
  - kiwisolver=1.4.4
  - llvmlite=0.39.1
  - matplotlib=3.7.1
  - mpmath=1.3.0
  - numba=0.56.4
  - numpy=1.23.5
  - pandas=2.0.0
  - Pillow=9.5.0
  - pyparsing=3.0.9
  - pytz=2023.3
  - seaborn=0.12.2
  - simpy=4.0.1
  - sympy=1.11.1